### PR TITLE
#56 Branch: Jakarta Faces 3.0 - WIP

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by christophs78** [comment]
Seems to be a bit better than last autumn but still issues....

Startup currently fails with 
```
[WARNING] Failed startup of context o.e.j.m.p.MavenWebAppContext@6b2e46af{/,[file:///C:/Users/chris/IdeaProjects/christophs78_primefaces-test/src/main/webapp/, jar:file:///C:/Users/chris/.m2/repository/org/glassfish/jakarta.faces/3.0.0/jakarta.faces-3.0.0.jar!/META-INF/resources, jar:file:///C:/Users/chris/.m2/repository/org/primefaces/primefaces/10.0.0/primefaces-10.0.0-jakarta.jar!/META-INF/resources],UNAVAILABLE}{file:///C:/Users/chris/IdeaProjects/christophs78_primefaces-test/src/main/webapp/}
java.lang.RuntimeException: java.lang.LinkageError: loader constraint violation: when resolving interface method 'void jakarta.servlet.jsp.JspApplicationContext.addELResolver(jakarta.el.ELResolver)' the class loader org.eclipse.jetty.webapp.WebAppClassLoader @455c1d8c of the current class, com/sun/faces/config/ConfigureListener, and the class loader org.codehaus.plexus.classworlds.realm.ClassRealm @59429fac for the method's defining class, jakarta/servlet/jsp/JspApplicationContext, have different Class objects for the type jakarta/el/ELResolver used in the signature (com.sun.faces.config.ConfigureListener is in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @455c1d8c, parent loader org.codehaus.plexus.classworlds.realm.ClassRealm @59429fac; jakarta.servlet.jsp.JspApplicationContext is in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @59429fac, parent loader 'bootstrap')
    at com.sun.faces.config.ConfigureListener.contextInitialized (ConfigureListener.java:283)
    at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized (ContextHandler.java:1024)
    at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized (ServletContextHandler.java:624)
    at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized (ContextHandler.java:961)
    at org.eclipse.jetty.servlet.ServletHandler.initialize (ServletHandler.java:705)
```

**Comment by christophs78** [comment]
@GedMarc,  @melloware: Ideas on this? (Already googled for some time without success.)

**Comment by melloware** [comment]
Are you running with `mvn clean jetty:run` it might be a bug with the Jetty Maven Plugin.

**Comment by christophs78** [comment]
> Are you running with `mvn clean jetty:run` it might be a bug with the Jetty Maven Plugin.

same with `mvn clean jetty:run`

**Comment by melloware** [comment]
Feels like a classloader bug with the maven plugin.  And it fails with standalone Jetty 11.0.2 as well?

**Comment by christophs78** [comment]
Got it kind of running with Tomcat 10. (Standalone)
FacesServlet, (Faces-)Lifecycle, ... are executed, but raw XHTML is sent to the client...
image

**Comment by christophs78** [comment]
It´s due to https://github.com/eclipse-ee4j/mojarra/commit/c371b717328b3faf92d2a60dac6ea71b9afa110c#diff-93541ebe5766d37fe7a04667b74930124a32998cba7a31ac3b8da725feb0e646.

**Comment by christophs78** [comment]
> Feels like a classloader bug with the maven plugin. And it fails with standalone Jetty 11.0.2 as well?

Yep. Got it running on Tomcat 10. How can we get rid of the classloader-bug of jetty-maven-plugin?

**Comment by melloware** [comment]
I think we should report it to the maven Jetty plug-in project and provide the reproducer.

**Comment by christophs78** [comment]
Thanks to the feedback from the jetty-team we are up and running.
Can we create a Jakarta-branch? Or do we need some PrimeTek-member for this?
We don´t want to merge this into master...

**Comment by tandraschko** [comment]
Why not use owb?

**Comment by christophs78** [comment]
> Why not use owb?

Is there a Jakarta-release of owb?

**Comment by melloware** [comment]
@christophs78 I just created a "jakarta" branch here in PrimeFaces Test.

**Comment by melloware** [comment]
Unless you want branches for jakarta30, jakarta40, myfaces30, myfaces40 ?

**Comment by christophs78** [comment]
> Unless you want branches for jakarta30, jakarta40, myfaces30, myfaces40 ?

Thanks! I think/hope we can do the Mojarra/MyFaces 3/4 thing with maven profiles inside the Jakarta-branch.

**Comment by melloware** [comment]
OK will leave it just called jakarta then! Thanks for looking into this!

**Comment by GedMarc** [comment]
I've got a full suite for mojarra up and running, there's just a compile bug in EL for jdk 14 where they use the new keyword "yield" as a method name, so it doesn't compile in anything 14 and up (https://github.com/eclipse-ee4j/el-ri/issues/122)

JSTL also isn't loading for me, i'm missing something to do with new TLD namespace or something, either way, TLD's just don't work - trying to figure it out

**Comment by melloware** [comment]
So one thing I noticed is their docs say the namespace should be `http://jakarta.ee/xml/ns/jakartaee/`

See: https://jakarta.ee/xml/ns/jakartaee/

But in Eclispe the schema wouldn't validate because the namespace is really `https:` not `http:`

```xml
<facelet-taglib xmlns="https://jakarta.ee/xml/ns/jakartaee"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-facelettaglibrary_3_0.xsd"
                version="3.0">
```

**Comment by melloware** [comment]
And @GedMarc you are saying even after fixing the PrimeFaces TLD to the above namepsace it still doesn't work for you in tools?

**Comment by christophs78** [comment]
There are some weird things with primefaces-p.taglib.xml on IntelliJ

1. After changing the namespace as noted by @melloware it look´s like description-element is not allowed any more. (And i can´t find it in the XSD (yet).)
image

2. We relocate primefaces-p.taglib.xml to jakarta during building primefaces-XX.0.0-SNAPSHOT-jakarta.jar, but this does not touch the namespace.

3. IntelliJ does not recognize and e.g. offer autocomplete-support for PrimeFaces-taglib when on jakarta.
(Old and new namespace.)
image
For f: this works...
image

**Comment by christophs78** [comment]
Even EL-autocomplete is broken in IntelliJ for Jakarta - see https://youtrack.jetbrains.com/issue/IDEA-254486.
And there are some more issues https://youtrack.jetbrains.com/issue/IDEA-244772.
It does not look like this get´s fixed for upcoming 2021.1
@BalusC, @arjantijms - is there some communication-channel between eclipse-foundation and JetBrains?
IntellliJ is IMO the primary IDE for most developers today. Missing/broken support for Jakarta Server Faces is not good at all.
(JetBrains marketing says they support Jakarta EE9. https://blog.jetbrains.com/idea/2020/07/intellij-idea-2020-2-eap6-jakarta-ee-9-quarkus-swagger-http-client-and-more/ But probably marketing with a bunch of real-world issues.)

**Comment by melloware** [comment]
I only have an open source free license to IntelliJ but I am wondering if we all log in and upvote those issues it may help?

**Comment by melloware** [comment]
I upvoted both issues.

**Comment by arjantijms** [comment]
@christophs78 I've been working a little to address exactly this issue when I was in the Jakarta Spec committee (representing Payara), but as you can see didn't get really far.

There was some debate about going for a Jakarta EE Language Server instead of donating code by e.g. Red Hat (who has their own Facelets / EL tooling for RH Eclipse Studio). It seems that such effort was recently started, see:

https://github.com/eclipse/lsp4jakarta

**Comment by GedMarc** [comment]
On the IntelliJ Autocomplete, I opened a bug (and closed after) for fixing the faces-config and taglib's to the right namespaces, 
This sorts out the autocomplete and the description tags in the XSD for IntelliJ @christophs78 - not a bug in IntelliJ but the library just packing wrong namespaces in the jakarta artifact 

Thanks for the ping, Still having my TLD issues with JSTL - but making some progress -

**Comment by christophs78** [comment]
Hi @GedMarc!

1. You think about p:XXX - autocomplete and primefaces-p.taglib.xml?
I played around a bit with this last weekend and did not find a way to modifiy this which works with IntelliJ and this Jakarata Server Faces - branch. Did you figure out a way that works?
2. Does EL-autocompletion work for you in IntellliJ with Jakarta Server Faces? (This part may be somehow related to faces-config.xml)

**Comment by GedMarc** [comment]
Yeah there was a trick to it :)

I've got a shade here - (https://github.com/GedMarc/GuicedEE-Services/tree/master/primefaces)
where I overwrite the taglib from the 10-release and migrate all dependencies etc to jakarta ...and place in the module-info to be JDK 11 compliant (maybe take a look at that for an idea on getting compatible for 11?)

https://github.com/GedMarc/GuicedEE-Services/tree/master/primefaces/src/main/resources/META-INF

This does the autocomplete correctly in IntelliJ - 

maven coords here - 

https://mvnrepository.com/artifact/com.guicedee.services/primefaces

**Comment by christophs78** [comment]
Do you do the shading automated?
If yes, i´d like to add this to our PrimeFaces pom.xml to create the correct PrimeFaces-Jakarta-JAR OOTB. (We already have some shading, but not enough.)

**Comment by melloware** [comment]
@christophs78 @GedMarc Yes I would like to get this ticket resolved in PrimeFaces Core: https://github.com/primefaces/primefaces/issues/7087

**Comment by christophs78** [comment]
Maybe we need to provide a JAR for JSF3 und one for JSF4, because they have different namespaces.

**Comment by christophs78** [comment]
Just updated to IntelliJ 2021.1 (from 2020.3) and now Autocomplete for PrimeFaces-Components and EL seems to work. Even with the Jakarta-version of PrimeFaces 10.0.0. 
Maybe it´s kind of confidence because i can´t find a official not on this. But it still works after invalidating IntelliJ-Caches.

**Comment by melloware** [comment]
Nice!

**Comment by tandraschko** [comment]
the jakarta branch works fine for me, i will close this

**Pull request closed without merging**
