### PR TITLE
# 56 Jakarta-branch

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Review by melloware — APPROVED** [review]
Nice work!

**Comment by melloware** [comment]
Adding @GedMarc as he was interested in this as well.

**Comment by GedMarc** [comment]
Thanks Mello :) 

Did you manage to get the TLD's working? I don't see any JSTL references in the test here but I've been struggling with it for a while now, Did you encounter issues with JSTL or TLD loading when loading up the jakarta namespace?

**Comment by melloware** [comment]
@GedMarc see the comment here about the TLD: https://github.com/primefaces/primefaces-test/pull/76#issuecomment-812908624

**Comment by christophs78** [comment]
Can we merge this PR into the jakarta-branch. We can always further improve. :-)

**Pull request merged**
